<style>
    .ui-autocomplete {
        z-index: 10000000;
    }

    .search-container {
        position: relative;
        display: flex;
        align-items: center;
        width: 100%;
    }

    .search-ico {
        cursor: pointer;
        fill: #ccc; /* Change the color as needed */
    }

    #search {
        width: 0;
        padding: 10px;
        box-sizing: border-box;
        border: none;
        outline: none;
        transition: width 0.3s ease;
        visibility: hidden;
        opacity: 0;
    }

    .search-container.active #search {
        width: 100%;
        visibility: visible;
        opacity: 1;
        border: 1px solid #ccc; /* Add border to make input visible when active */
        padding: 10px 10px 10px 40px; /* Adjust padding for the icon */
    }

    .filter {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>

<div class="filter">
    <form id="search-form" method="get" action="">
        <div class="search-container">
            <svg role="img" width="20" height="21" class="search-ico">
                <use xlink:href="#search"></use>
            </svg>
            <input type="text" name="search" id="search" autocomplete="off" placeholder="Search" />
        </div>
    </form>
</div>
<svg style="display:none;">
    <symbol id="search" viewBox="0 0 24 24">
        <path d="M15.5 14h-.79l-.28-.27a6.471 6.471 0 001.48-5.34C15.58 5.59 13.19 3.5 10 3.5S4.42 5.59 4.09 8.39a6.471 6.471 0 001.48 5.34l-.27.27h-.79l-4.99 5c-.19.18-.3.44-.3.71s.11.53.3.71c.19.18.44.29.71.29s.53-.11.71-.29l4.99-5 .27.27v.79l5 5c.18.19.44.3.71.3s.53-.11.71-.3c.18-.19.29-.44.29-.71s-.11-.53-.29-.71l-5-5v-.79l.27-.27c.87.61 1.91.97 3.03.97 2.66 0 5.05-2.09 5.05-4.75 0-2.66-2.09-4.75-4.75-4.75zM10 13c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3z"/>
    </symbol>
</svg>

<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($) { 
    $(document).ready(function() {
        var metaDataArray = <?php echo $block->getMetaData(); ?>;


        $('.search-ico').on('click', function() {
            $('.search-container').toggleClass('active');
            if ($('.search-container').hasClass('active')) {
                $('#search').focus();
            }
        });

        $('#search').autocomplete({
            source: function(request, response) {
                var matcher = new RegExp($.ui.autocomplete.escapeRegex(request.term), "i");
                response($.grep(metaDataArray, function(value) {
                    return matcher.test(value.label) || matcher.test(value.description);
                }));
            },
            minLength: 2,
            select: function(event, ui) {
                
                event.preventDefault();
                
                window.location.href = ui.item.value;
                $('#search-form')[0].reset();
            }
        }).data('ui-autocomplete')._renderItem = function(ul, item) {
            return $('<li>')
                .append($('<a>').attr('href', item.value)
                    .append($('<div>').text(item.label))
                )
                .appendTo(ul);
        };
        $('.searchbox-icon').on('click', function() {
            $('#search').toggle().focus();
        });
    });
});
</script>
