<?php
/** @var \Apetito\Search\Block\Index\Index $block */
//get query and metadata from block file
$query = $block->getData('query');
$metaDataJson = $block->getMetaData();
$showMetaDesc = $block->isMetaDescriptionEnable();
//convert the metadata into JSON
$metaDataArray = json_decode($metaDataJson, true);
//The array_filter() function filters the values of an array using a callback function.
//This function passes each value of the input array to the callback function. If the callback function returns true, the current value from input is returned into the result array. Array keys are preserved.
//The stripos() function finds the position of the first occurrence of a string inside another string.

$filteredResults = array_filter($metaDataArray, function($item) use ($query) {
    return @stripos($item['searchData'], $query) !== false;
});
?>
<?php
    echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('search_result_images')
        ->toHtml();
?>
<div class="search-results-container">
    <h1><?php echo __('Search Results for "%1"', $query); ?></h1>
</div>
<div class="searchres-list">
    <?php if (count($filteredResults) > 0): ?>
        <div>
            <ul>
                <?php foreach ($filteredResults as $result): ?>
                    <li>
                        <div>
                            <a target="_blank" href="<?php echo $result['value']; ?>">
                            <div class="searchres-head">
                                    <h3><?php echo $result['label']; ?></h3>
                                    <?php if ($showMetaDesc) { ?>
                                        <p><?php echo $result['description']; ?></p>
                                    <?php } ?>
                                </div>
                            </a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php else: ?>
        <div>
            <p class="search-no-results"><?php echo __('Unfortunately there are no results for "%1", visit our news page to stay up to date with the latest advancements at apetito.', $query); ?></p>
        </div>
    <?php endif; ?>
</div>

